export default {
  default: {
    Wave: {
      width: ['100%', '960px'],
      marginTop: '40px',
      marginLeft: [0, 'calc(50% - 480px)'],
      marginBottom: '40px',
      position: 'relative',
      display: ['block', 'flex'],
    },
    ScrollerContainer: {
      flex: 1,
      paddingLeft: [0, '50px'],
      paddingTop: ['50px', 0],
    },
    ScrollerContainerRight: {
      flex: 1,
      paddingRight: [0, '50px'],
      paddingTop: ['50px', 0],
    },
    ScrollerStep: {
      position: 'relative',
      padding: [0, '0 10px'],
      minHeight: '250px',
      display: 'flex',
      alignItems: 'center',
      borderLeft: ['none', '3px solid transparent'],
    },
    ScrollerProgress: {
      position: 'absolute',
      left: ['-12px', '-3px'],
      backgroundColor: 'primary',
    },
    ScrollerProgressRight: {
      position: 'absolute',
      right: ['-12px', '-3px'],
      backgroundColor: 'primary',
    },
    StickerContainer: {
      width: ['100vw', '50%'],
      marginLeft: ['calc(50% - 50vw)', 0],
      position: ['sticky', 'static'],
      top: [0, 'auto'],
      zIndex: [1, 'auto'],
      height: ['50vh', 'auto'],
    },
    Sticker: {
      position: ['static', 'sticky'],
      width: '100%',
      height: ['100%', '60vh'],
      top: ['auto', '20vh'],
    },
    SVGSticker: {
      position: ['static', 'sticky'],
      width: '100%',
      // height: ['100%', '30vh'],
      // top: ['auto', '30vh'],
      // border: ["none", "1px solid"],
      // borderColor: "secondary",
      height: ['100%', 'calc(480px * 9 / 16)'],
      top: ['auto', 'calc(50vh - 480px * 9 / 32)'],
      overflow: 'hidden',
      // boxShadow: '0 20px 50px 0 rgba(0,0,0,0.3)',
      borderRadius: '5px',
      padding: '20px',
    },
    focus: [0.7, 0.5],
  },
}
